//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUN2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(AbonnentenLehrstuhlMetadata))]
    public partial class AbonnentenLehrstuhl
    {
        public string userid { get; set; }
        public int lehrstuhlid { get; set; }
    }
}
