//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUN2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [MetadataType(typeof(GruppeMetadata))]
    public partial class Gruppe
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int gruppenid { get; set; }
        [StringLength(400, MinimumLength = 10)]
        [Required]
        public string bezeichnung { get; set; }
        [StringLength(1500, MinimumLength = 10)]
        [Required]
        public string beschreibung { get; set; }
        public string verantwortlicher { get; set; }
        public Nullable<bool> privat { get; set; }
    }
}
