//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUN2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LehrstuhlEintraege
    {
        public string id { get; set; }
        public string lehrstuhlid { get; set; }
        public System.DateTime datum { get; set; }
        public string autor { get; set; }
        public string inhalt { get; set; }
        public string label1 { get; set; }
        public string label2 { get; set; }
        public string label3 { get; set; }
        public string label4 { get; set; }
        public string label5 { get; set; }
    }
}
