//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUN2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [MetadataType(typeof(LehrstuhlEintraegeMetadata))]
    public partial class LehrstuhlEintraege
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        public int lehrstuhlid { get; set; }
        public System.DateTime datum { get; set; }
        public string autor { get; set; }
        [StringLength(2500, MinimumLength = 15)]
        public string inhalt { get; set; }
        [StringLength(150, MinimumLength = 0)]
        public string label1 { get; set; }
        [StringLength(150, MinimumLength = 0)]
        public string label2 { get; set; }
                [StringLength(150, MinimumLength = 0)]
        public string label3 { get; set; }
        [StringLength(150, MinimumLength = 0)]
        public string label4 { get; set; }
        [StringLength(150, MinimumLength = 0)]
        public string label5 { get; set; }
    }
}
