//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUN2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SUN2Entities : DbContext
    {
        public SUN2Entities()
            : base("name=SUN2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

        public System.Data.Entity.DbSet<SUN2.Models.Lehrstuhl> Lehrstuhls { get; set; }

        public System.Data.Entity.DbSet<SUN2.Models.AbonnentenLehrstuhl> AbonnentenLehrstuhls { get; set; }

        public System.Data.Entity.DbSet<SUN2.Models.Gruppe> Gruppes { get; set; }

        public System.Data.Entity.DbSet<SUN2.Models.GruppenEintraege> GruppenEintraeges { get; set; }

        public System.Data.Entity.DbSet<SUN2.Models.LehrstuhlEintraege> LehrstuhlEintraeges { get; set; }

        public System.Data.Entity.DbSet<SUN2.Models.MitarbeiterLehrstuhl> MitarbeiterLehrstuhls { get; set; }

        public System.Data.Entity.DbSet<SUN2.Models.MitgliederGruppe> MitgliederGruppes { get; set; }
    }
}
